services:
  - type: web
    name: streamlit-interface
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py
    envVars:
      - key: PORT
        value: 10000
